name: Build Friday Fight Funkin'

on:
  schedule:
    - cron: '0 23 * * 5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildforwindows:
    name: Build Windows 64-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v6.1.0
        with:
          path: Library
          key: Library-Windows64-${{ hashFiles('ProjectSettings/ProjectVersion.txt', 'Packages/manifest.json', 'Packages/packages-lock.json') }}
      - uses: game-ci/unity-builder@v6.0.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: StandaloneWindows64
          versioning: Semantic
          buildName: Funkin
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: FridayFightFunkin-Windows64
          path: build/StandaloneWindows64
          if-no-files-found: error
